### ISSUE TITLE
Rendered output is in quotes

### ISSUE THREAD

**Issue by jusjoe99** [ellmetha/django-precise-bbcode#7] opened 2015-07-28 00:01 UTC
Whenever I render a text field(via the template filter) or if I use a BBCodeTextField and use .render both output with surrounding double quotes. Thus not applying the tags
Example:
If the field holds: ```[b]Hello[/b]```
The output would be: ```"<strong>Hello</strong>"```

**Comment by ellmetha** [comment] 2015-07-28 04:03
Hi,
Thanks for reporting this potential issue. I am not able to reproduce it for now. Could you be more specific regarding your project configuration/environment? Which version of python do you use? Which version of Django? Which database backend?
Are you using the latest version of *django-precise-bbcode*? Do you use the ``safe`` filter  tag when trying to display your bbcode contents in your templates? Can you paste a copy of the code highlighting how you are trying to display your bbcodes?

Note that for now the ``rendered`` value of a BBCodeTextField instance is not explicitly marked as safe for HTML output purposes. Maybe your problem is related to this. I will patch this soon. ;)

**Comment by jusjoe99** [comment] 2015-07-28 04:58
The safe filter fixed it, thanks!

Here's the information anyway:
I'm running Django 1.7.8, Python Version 2.7.9

Here's the code snippet:
[http://pastebin.com/SnkHSc8a](http://pastebin.com/SnkHSc8a)

**Comment by ellmetha** [comment] 2015-07-28 13:29
OK. Aniway I'll patch this behavior. It's a bit disturbing to have to use the ``safe`` filter to display BBCodeTextField contents.
Thanks again. ;)

**Closed by ellmetha** 2015-07-28 13:29 UTC
